#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "${BASH_SOURCE[0]}")
source constants

if [[ $# != 1 ]]; then
    echo "Usage: $0 <root-pass>"
    exit 1
fi

PASSWORD="$1"

docker build -t uflix/main \
    --build-arg plex_home=$PLEX_HOME \
    --build-arg password=$PASSWORD \
    .
