#!/usr/bin/env bash
set -euo pipefail
cd $(dirname "${BASH_SOURCE[0]}")
source constants

# configuration
SSH_PORT=2200
HOSTNAME="plex-uflix"


if [[ $(id -u) != 0 ]]; then
    echo "Please run this script as a root user"
    exit 2
fi

if [[ $# != 1 ]]; then
    echo "Usage: $0 <luks encrypted drive>"
    exit 1
fi

PLEX_DEVICE="$1"

# Open the encrypted drive
PLEX_MAPPED="uflix-data-$$"
PLEX_MOUNT="/mnt/$PLEX_MAPPED"
# make sure dm-crypt & dm-mod module is loaded
modprobe dm-crypt
modprobe dm-mod
cryptsetup open --type luks $PLEX_DEVICE $PLEX_MAPPED
mkdir -p $PLEX_MOUNT
mount "/dev/mapper/$PLEX_MAPPED" $PLEX_MOUNT

docker run \
    -h $HOSTNAME \
    -p $SSH_PORT:22 \
    -v $PLEX_MOUNT:$PLEX_HOME \
    -p 32400:32400 \
    -p 32400:32400/udp \
    -p 32469:32469 \
    -p 32469:32469/udp \
    -p 5353:5353/udp \
    -p 1900:1900/udp \
    uflix/main

# remove the encrypted drive
umount $PLEX_MOUNT
rmdir $PLEX_MOUNT
cryptsetup remove $PLEX_MAPPED

