#!/usr/bin/env bash
set -euo pipefail

source /etc/environment

for DIR in 'Movies' 'TV Shows' 'Music' 'Photos' 'Home Videos'; do
    if [[ ! -d "${PLEX_HOME}/${DIR}" ]]; then
        mkdir -p "${PLEX_HOME}/${DIR}"
    fi
done

chown plex:plex -R "${PLEX_HOME}"

if [[ ! $(ps -A | grep avahi-daemon) ]]; then
    echo 'Avahi has not started, not starting Plex yet.'
    exit 1
fi

echo "Starting Plex Media Server..."
exec 2>&1
exec chpst -u plex /usr/sbin/start_pms
