#!/usr/bin/env bash
set -euo pipefail

if [[ -e /var/run/dbus.pid ]]; then
	rm /var/run/dbus.pid
fi

if [[ ! -x /var/run/dbus ]]; then
	install -m755 -g 81 -o 81 -d /var/run/dbus
fi

if [[ -x /usr/bin/dbus-uuidgen ]]; then
	dbus-uuidgen --ensure
fi

echo "Starting DBus Daemon..."
exec dbus-daemon --system --nofork --nopidfile
